### PR TITLE
run error

### PR DESCRIPTION
**Pull request by szamuboy**
Hey thanks for this!

`nix run github:szamuboy/wasm4-nix` is failing for me with 
> error: cannot find flake attribute 'github:szamuboy/wasm4-nix#defaultApp.x86_64-linux'

Is there something I could be missing?

### CODE REVIEW

**Comment by szamuboy** [comment]
Hi @hazeycode! 

Thank you for reporting the issue. I'm a nix newbie, but I like to troubleshoot this failure.

I couldn't reproduce your problem in my environment. What is the version of nix you are using?

In my case, it's
```bash
$ nix --version
nix (Nix) 2.8.1
```

**Comment by hazeycode** [comment]
Oh, I am using a quite old version of nix, 2.4.
I will have to upgrade my env and report back.
Thanks!

**Comment by szamuboy** [comment]
Thanks! I suspect that [this](https://github.com/NixOS/nix/issues/5532) changed the flake format. I guess you need nix 2.7 or newer.

**Comment by hazeycode** [comment]
I have upgraded to nix 2.8.1 and it now works perfectly!

**Pull request merged**
